<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.pocketwatch</groupId>
		<artifactId>pocket-watch</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>pocket-watch-validator</artifactId>
	<packaging>jar</packaging>

	<name>PocketWatch Validator</name>
	<description>Runtime validation engine using reflection</description>


	<dependencies>
		<!-- Internal dependencies -->
		<dependency>
			<groupId>io.pocketwatch</groupId>
     		 <artifactId>pocket-watch-core</artifactId>
		</dependency>

		<dependency>
			<groupId>io.pocketwatch</groupId>
			<artifactId>pocket-watch-annotations</artifactId>
		</dependency>

		<!-- Logging -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>

		<!-- Testing -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>
	</dependencies>

</project>